name: glue_deployment
on: [push]
env:
  super_secret: ${{ secrets.PRIVATE_KEY }} 
  
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ssh into ec2 & deploy the code
        run: |
          echo $super_secret
