name: glue_deployment
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ssh into ec2 & deploy the code
        run: |
          echo ${{ secrets.PRIVATE_KEY }} 
