name: lambda_layer_test
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4ASLMUJL3LCBXNAL
          aws-secret-access-key: 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
          aws-region: us-east-1
      -  name: Creating deployment zip
         run: |
           sudo apt install zip
           mkdir -p ./deployment_zip 
           pip install snowflake-connector-python -t ./deployment_zip
           cp ./snowflake_lambda_code.py  ./deployment_zip
           cd ./deployment_zip
           zip -r ./deployment_zip/lambda_zip.zip ./deployment_zip
      - name: Upload to s3
        run: |
          cd ./deployment_zip
          aws s3 cp ./deployment_zip/lambda_zip.zip s3://normaldatapoint
          aws lambda update-fucntion-code --function-name snowflake_lambda_cicd --zip-file s3://normaldatapoint/lambda_zip.zip
