name: glue_deployment
on: [push]
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} 
  
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ssh into ec2 & deploy the code
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-user@ec2-54-221-140-186.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/demogithubactionyttest"
