name: second_github_action
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "text": "Deployment started (In Progress)",
            "attachments": [
            {
            "pretext": "Deployment started",
            "color": "dbab09",
            "fields": [
            {
            "title": "Status",
            "short": true,
            "value": "In Progress"
            }
            ]
            }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
